default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: vaicar_backend_development

test:
  <<: *default
  database: vaicar_backend_test

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>
  username: vaicar_backend
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>
